# Generated by Django 2.0.6 on 2018-07-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cilindraje', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dimensiones', models.CharField(max_length=500)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('matricula', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=500)),
                ('fecha_inicio', models.CharField(max_length=500)),
                ('fecha_final', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('direccion', models.CharField(max_length=500)),
                ('lugar_nacimiento', models.CharField(max_length=500)),
                ('web', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=500)),
                ('web', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('direccion', models.CharField(max_length=500)),
                ('lugar_nacimiento', models.CharField(max_length=500)),
                ('web', models.CharField(max_length=500)),
                ('auto', models.ManyToManyField(blank=True, null=True, to='home2.Auto')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home2.Patrocinador')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='mecanico',
            field=models.ManyToManyField(blank=True, null=True, to='home2.Mecanico'),
        ),
    ]
