# Generated by Django 2.0.6 on 2018-07-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='competidores',
            field=models.ManyToManyField(blank=True, null=True, to='home2.Piloto'),
        ),
    ]
