# Generated by Django 2.0.6 on 2018-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0003_auto_20180731_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autos'),
        ),
    ]
