# Generated by Django 2.0.6 on 2018-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0004_auto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pilotos'),
        ),
    ]
