# Generated by Django 2.0.6 on 2018-08-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0006_carrera_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mecanicos'),
        ),
    ]
