# Generated by Django 2.0.6 on 2018-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0009_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='detalle',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
