# Generated by Django 2.0.6 on 2018-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0010_auto_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='detalle',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
