# Generated by Django 2.0.6 on 2018-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home2', '0011_auto_20180823_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='detalle',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='mecanico',
            name='detalle',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='detalle',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='piloto',
            name='detalle',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
